# Generated by Django 4.1.10 on 2023-11-16 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pcgroups", "0003_remove_playergroup_db_squads_squad_db_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="squad",
            name="db_group",
        ),
        migrations.AddField(
            model_name="playergroup",
            name="db_squads",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pcgroups.squad",
            ),
        ),
    ]
