# Generated by Django 4.1.10 on 2023-11-16 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pcgroups", "0004_remove_squad_db_group_playergroup_db_squads"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playergroup",
            name="db_squads",
        ),
        migrations.AddField(
            model_name="squad",
            name="db_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pcgroups.playergroup",
            ),
        ),
    ]
