# Generated by Django 4.1.11 on 2023-09-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("objects", "0014_defaultobject_defaultcharacter_defaultexit_and_more"),
        ("roster", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "db_date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="date created"
                    ),
                ),
                (
                    "db_members",
                    models.ManyToManyField(blank=True, to="objects.objectdb"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PlayerAccount",
        ),
        migrations.DeleteModel(
            name="Roster",
        ),
    ]
