# Generated by Django 4.1.10 on 2024-01-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("combat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="busterlist",
            name="db_description",
            field=models.TextField(blank=True, null=True, verbose_name="File"),
        ),
        migrations.AddField(
            model_name="weapon",
            name="db_description",
            field=models.TextField(blank=True, null=True, verbose_name="File"),
        ),
    ]
