# Generated by Django 4.1.10 on 2024-01-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("combat", "0002_busterlist_db_description_weapon_db_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busterlist",
            name="db_description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="db_description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
