# Generated by Django 4.1.10 on 2023-11-09 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("objects", "0014_defaultobject_defaultcharacter_defaultexit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_title", models.CharField(max_length=200, verbose_name="Name")),
                ("db_text", models.TextField(blank=True, verbose_name="File")),
                (
                    "db_date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="date created"
                    ),
                ),
                ("db_author", models.CharField(max_length=200, verbose_name="Author")),
                (
                    "up_to_date",
                    models.BooleanField(default=True, verbose_name="Up to date?"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_title", models.CharField(max_length=200, verbose_name="Title")),
                ("db_message_body", models.TextField(verbose_name="Message Body")),
                (
                    "db_date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="date created"
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "General"),
                            (2, "Bugfix"),
                            (3, "Character"),
                            (5, "Build"),
                            (6, "Auto"),
                            (4, "ICNews"),
                            (7, "Research"),
                            (8, "Activity"),
                            (9, "HelpFile"),
                        ]
                    ),
                ),
                ("db_is_open", models.BooleanField(default=True, verbose_name="Open")),
                (
                    "db_assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Assigned_to",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "db_copied_to",
                    models.ManyToManyField(
                        blank=True, related_name="Copied_to", to="objects.objectdb"
                    ),
                ),
                (
                    "db_submitter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Submitter",
                        to="objects.objectdb",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_name", models.CharField(max_length=2000, verbose_name="Name")),
                (
                    "db_date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="date created"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RequestResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_text", models.TextField(blank=True, verbose_name="Response")),
                (
                    "db_date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="date created"
                    ),
                ),
                (
                    "db_was_read",
                    models.BooleanField(default=False, verbose_name="Read"),
                ),
                (
                    "db_author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="author",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "db_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Request",
                        to="requests.request",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "db_key",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Keyword"
                    ),
                ),
                ("db_files", models.ManyToManyField(to="requests.file")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="file",
            name="db_topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="requests.topic",
            ),
        ),
    ]
