# Generated by Django 4.1.10 on 2023-11-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="db_submitter",
            field=models.CharField(
                default="Player", max_length=200, verbose_name="Submitter"
            ),
        ),
    ]
