# Generated by Django 4.1.10 on 2023-11-14 23:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("requests", "0002_rename_db_key_keyword_db_keyword_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="File",
        ),
        migrations.DeleteModel(
            name="Keyword",
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
