# Generated by Django 4.1.10 on 2023-08-12 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("combat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Capability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "db_date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="date created"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArmorMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "db_date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="date created"
                    ),
                ),
                (
                    "db_swap",
                    models.IntegerField(
                        choices=[
                            (1, "Mode"),
                            (2, "Stance"),
                            (3, "Focus"),
                            (4, "Form"),
                            (5, "VR"),
                            (6, "Summon"),
                            (7, "Minion"),
                            (8, "System"),
                            (9, "Armor"),
                        ],
                        default=1,
                        verbose_name="Swap Style",
                    ),
                ),
                ("db_pow", models.IntegerField(default=1, verbose_name="Power")),
                ("db_dex", models.IntegerField(default=1, verbose_name="Dexterity")),
                ("db_ten", models.IntegerField(default=1, verbose_name="Tenacity")),
                ("db_cun", models.IntegerField(default=1, verbose_name="Cunning")),
                ("db_edu", models.IntegerField(default=1, verbose_name="Education")),
                ("db_chr", models.IntegerField(default=1, verbose_name="Charisma")),
                ("db_aur", models.IntegerField(default=1, verbose_name="Aura")),
                (
                    "db_size",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Size"
                    ),
                ),
                ("db_speed", models.IntegerField(default=1, verbose_name="Speed")),
                (
                    "db_strength",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Strength"
                    ),
                ),
                (
                    "db_resistance",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Resistance"
                    ),
                ),
                (
                    "db_weakness",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Weakness"
                    ),
                ),
                ("db_discern", models.IntegerField(default=1, verbose_name="Discern")),
                ("db_aim", models.IntegerField(default=1, verbose_name="Aim")),
                (
                    "db_athletics",
                    models.IntegerField(default=1, verbose_name="Athletics"),
                ),
                ("db_force", models.IntegerField(default=1, verbose_name="Force")),
                (
                    "db_mechanics",
                    models.IntegerField(default=1, verbose_name="Mechanics"),
                ),
                (
                    "db_medicine",
                    models.IntegerField(default=1, verbose_name="Medicine"),
                ),
                (
                    "db_computer",
                    models.IntegerField(default=1, verbose_name="Computer"),
                ),
                ("db_stealth", models.IntegerField(default=1, verbose_name="Stealth")),
                ("db_heist", models.IntegerField(default=1, verbose_name="Heist")),
                (
                    "db_convince",
                    models.IntegerField(default=1, verbose_name="Convince"),
                ),
                (
                    "db_presence",
                    models.IntegerField(default=1, verbose_name="Presence"),
                ),
                ("db_arcana", models.IntegerField(default=1, verbose_name="Arcana")),
                (
                    "db_busterlist",
                    models.ManyToManyField(blank=True, to="combat.busterlist"),
                ),
                (
                    "db_capabilities",
                    models.ManyToManyField(blank=True, to="armor.capability"),
                ),
                (
                    "db_primary",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_weapon",
                        to="combat.weapon",
                    ),
                ),
                (
                    "db_secondary",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_weapon",
                        to="combat.weapon",
                    ),
                ),
                ("db_weapons", models.ManyToManyField(blank=True, to="combat.weapon")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
