# Generated by Django 4.1.10 on 2023-08-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("armor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="armormode",
            name="db_size",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Size"
            ),
        ),
        migrations.AlterField(
            model_name="armormode",
            name="db_speed",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Speed"
            ),
        ),
        migrations.AlterField(
            model_name="armormode",
            name="db_strength",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Strength"
            ),
        ),
    ]
