# Generated by Django 4.1.10 on 2023-08-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("armor", "0002_alter_armormode_db_size_alter_armormode_db_speed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="armormode",
            name="db_speed",
            field=models.IntegerField(default=1, verbose_name="Speed"),
        ),
    ]
