# Generated by Django 4.1.10 on 2023-11-09 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("combat", "0001_initial"),
        ("armor", "0003_alter_armormode_db_speed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="armormode",
            name="db_primary",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_weapon",
                to="combat.weapon",
            ),
        ),
        migrations.AlterField(
            model_name="armormode",
            name="db_secondary",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="secondary_weapon",
                to="combat.weapon",
            ),
        ),
    ]
