# Generated by Django 4.1.10 on 2023-11-14 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "db_keyword",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Keyword"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_name", models.CharField(max_length=2000, verbose_name="Name")),
                (
                    "db_date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="date created"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_title", models.CharField(max_length=200, verbose_name="Name")),
                ("db_text", models.TextField(blank=True, verbose_name="File")),
                (
                    "db_date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="date created"
                    ),
                ),
                ("db_author", models.CharField(max_length=200, verbose_name="Author")),
                (
                    "up_to_date",
                    models.BooleanField(default=True, verbose_name="Up to date?"),
                ),
                ("db_keywords", models.ManyToManyField(blank=True, to="files.keyword")),
                (
                    "db_topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="files.topic",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
